# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm

    working_directory: ~/app

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile # https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache ## cache both yarn and Cypress!

      - run:
          name: Setup custom environment variables
          command: |
            echo 'export CYPRESS_DASHBOARD_KEY=$CYPRESS_DASHBOARD_KEY' >> $BASH_ENV # Redirect $CYPRESS_DASHBOARD_KEY into $BASH_ENV

      - run:
          name: Run Unit and E2E tests in parallel
          command: yarn validate

      - run:
          name: Upload Unit Tests reports to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
