# CircleCI 2.1 configuration file
#
# Check https://github.com/cypress-io/circleci-orb for more details
#
version: 2.1

orbs:
  cypress: cypress-io/cypress@1.7.0

jobs:
  test:
    executor: cypress/base-10
    steps:
      - run: echo "Assuming dependencies were installed using cypress/install job"
      - attach_workspace:
          at: ~/
      - run:
          name: Run unit tests
          command: yarn test:coverage
      - run:
          name: Upload unit tests reports to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build-tests:
    jobs:
      # first get the source code and install npm dependencies
      - cypress/install:
          yarn: true # use yarn
          build: yarn build # run a custom app build step
      - test:
          # make sure app has been installed and built
          # before running tests across multiple machines
          # this avoids installing same dependencies 10 times
          requires:
            - cypress/install
      - cypress/run:
          # make sure app has been installed and built
          # before running tests across multiple machines
          # this avoids installing same dependencies 10 times
          requires:
            - cypress/install
          yarn: true # use yarn
          record: false # record results on Cypress Dashboard
          parallel: true # split all specs across machines
          parallelism: 3 # use 3 CircleCI machines to finish quickly
          group: e2e tests # name this group "all tests" on the dashboard
          start: yarn serve:e2e # start server before running tests
          wait-on: http://localhost:8000 # wait for server to respond
          store_artifacts: true # store screenshots and videos as a build artifacts
